package com.rohit.recon.recon.mapper;

import com.rohit.recon.recon.domain.DonationSearchResult;
import com.rohit.recon.recon.dto.DonationSearchResultDto;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

public class DonationSearchResultMapper {

    public static DonationSearchResult toEntity(DonationSearchResultDto dto) {
        return new DonationSearchResult(
                null, // ID will be autogenerated
                dto.getDetailLink(),
                dto.getEntityName(),
                dto.getRegister(),
                dto.getCampaigningName(),
                dto.getEntityType(),
                dto.getValue(),
                dto.getAcceptedDate(),
                dto.getReceivedBy(),
                dto.getDonorName(),
                dto.getReportedUnder6212(),
                dto.getIsSponsorship(),
                dto.getDonorStatus(),
                dto.getIsIrishSource(),
                dto.getRegulatedDoneeType(),
                dto.getCompanyRegNo(),
                dto.getPostcode(),
                dto.getDonationType(),
                LocalDateTime.now()
        );
    }

    public static List<DonationSearchResult> toEntityList(List<DonationSearchResultDto> dtoList) {
        return dtoList.stream()
                .map(DonationSearchResultMapper::toEntity)
                .collect(Collectors.toList());
    }
}