spring:
  application:
    name: recon

scraper:
  url: https://search.electoralcommission.org.uk/?currentPage=1&rows=10&query=Asylum&sort=AcceptedDate&order=desc&tab=1&open=filter&et=%7b0%3dpp%2c+1%3dppm%2c+2%3dtp%2c+3%3dperpar%2c+4%3drd%7d&isIrishSourceYes=true&isIrishSourceNo=true&date=Reported&from=&to=&quarters=2025Q1234&quarters=2024Q1234&quarters=2023Q1234&quarters=2020Q1234&quarters=2019Q1234&quarters=2018Q1234&quarters=2017Q1234&quarters=2016Q1234&quarters=2015Q1234&quarters=2014Q1234&quarters=2013Q1234&quarters=2012Q1234&quarters=2011Q1234&quarters=2010Q1234&quarters=2009Q1234&quarters=2008Q1234&quarters=2007Q1234&quarters=2006Q1234&quarters=2005Q1234&quarters=2004Q1234&quarters=2003Q1234&quarters=2002Q1234&quarters=2001Q1234&prePoll=false&postPoll=true&register=%7b0%3dgb%2c+1%3dni%2c+2%3dnone%7d&register=gb&register=ni&register=none&optCols=RegisterName&optCols=CampaigningName&optCols=AccountingUnitsAsCentralParty&optCols=IsSponsorship&optCols=IsIrishSource&optCols=RegulatedDoneeType&optCols=CompanyRegistrationNumber&optCols=Postcode&optCols=NatureOfDonation&optCols=PurposeOfVisit&optCols=DonationAction&optCols=ReportedDate&optCols=IsReportedPrePoll&optCols=ReportingPeriodName&optCols=IsBequest&optCols=IsAggregation

#scraper:
#  query-params:
#    query: RBS
#    currentPage: 1
#    rows: 10
#    sort: AcceptedDate
#    order: desc
#    tab: "1"
#    quarters: 2025Q1234
#    prePoll: false
#    postPoll: true
#    register:
#      - gb
#      - ni
#      - none
#    et:
#      - pp
#      - ppm
#      - tp
#      - perpar
#      - rd
#    isIrishSourceYes: true
#    isIrishSourceNo: true
#    optCols:
#      - RegisterName
#      - CampaigningName
#      - AccountingUnitsAsCentralParty
#      - IsSponsorship
#      - IsIrishSource
#      - RegulatedDoneeType
#      - CompanyRegistrationNumber
#      - Postcode
#      - NatureOfDonation
#      - PurposeOfVisit
#      - DonationAction
#      - ReportedDate
#      - IsReportedPrePoll
#      - ReportingPeriodName
#      - IsBequest
#      - IsAggregation